cashdj/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'', include('cashmgr.urls')),
    
    url(r'^cashmgr/', include('cashmgr.urls')),
    url(r'^cashmgr/admin/', admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cashmgr/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^incomplete/$', views.incomplete_transactions, name='index'),
    url(r'^add_account/$', views.add_account_dialog, name='Add Account Dialog'),
    url(r'^add/payee/$', views.add_payee, name='Add Payee'),
    url(r'^add/invoice/$', views.add_invoice, name='New Invoice'),
    url(r'^add/category/$', views.add_category, name='Add Category'),
    url(r'^add/account/$', views.add_account, name='Add Account Routine'),
    url(r'^import/$', views.upload_file, name='Upload a csv file'),
    url(r'^accounts/(?P<account_id>[0-9]+)/$', views.account_view, name='Account main view'),
    #url(r'^inline_payee_change/(?P<transaction_id>[0-9]+)/$', views.payee_change, name='ajax payee change'),
    url(r'^quick_add/(?P<transaction_id>[0-9]+)/$', views.quick_add, name='ajax quick add'),
    url(r'^delete/transaction/(?P<transaction_id>[0-9]+)/$', views.delete_transaction, name='delete transaction'),
    #url(r'^inline_category_change/(?P<transaction_id>[0-9]+)/$', views.category_change, name='ajax category change'),
    url(r'^inline/modify/transaction/(?P<transaction_id>[0-9]+)/$', views.modify_transaction_inline, name='ajax transaction change'),
    #url(r'^category/exists/$', views.category_exists, name='ajax category check'),
    #url(r'^payee/exists/$', views.payee_exists, name='ajax payee check'),
    url(r'^transactions/$', views.list_transactions, name='Transaction List'),
    url(r'^invoices/$', views.invoice_list, name='Invoice List'),
    url(r'^report_center/$', views.report_center, name='Report Center'),
    url(r'^report/$', views.create_report, name='Report'),
    url(r'^payees/$', views.payee_center, name='Payee'),
    url(r'^modify/payee/(?P<uid>[0-9]+)/$', views.modify_payee, name='Modify Payee'),
    url(r'^modify/invoice/(?P<pk>[0-9]+)/$', views.add_invoice, name='Modify Invoice'),
    url(r'^details/payee/(?P<uid>[0-9]+)/$', views.show_payee, name='Payee details'),
    #url(r'^recordinfo/(?P<model>\w+)/(?P<pk>[\w\W]+)/$', views.record_info, name='Record Info'),
    #url(r'^change/(?P<model>\w+)/(?P<pk>[\w\W]+)/(?P<ftype>\w+)/(?P<field>\w+)/$', views.change_field, name='Change field'),
    url(r'^preview/invoice/$', views.preview_invoice, name='Invoice Preview'),
    url(r'^query/record/$', views.query_record, name='Query a record'),
    
    
]

cashmgr/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import totsum, json_basic_serialize
import string
import json
from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
import datetime
import pytz

class JSONField(models.TextField):
    """
    JSONField is a generic textfield that neatly serializes/unserializes
    JSON objects seamlessly.
    Django snippet #1478

    example:
        class Page(models.Model):
            data = JSONField(blank=True, null=True)


        page = Page.objects.get(pk=5)
        page.data = {'title': 'test', 'type': 3}
        page.save()
    """

    def to_python(self, value):
        if value == "":
            return None

        try:
            if isinstance(value, str):
                return json.loads(value)
        except ValueError:
            pass
        return value

    def get_db_prep_save(self, value, *args, **kwargs):
        if value == "":
            return None
        if isinstance(value, dict):
            value = json.dumps(value, cls=DjangoJSONEncoder)
        return super(JSONField, self).get_db_prep_save(value, *args, **kwargs)


TRANSACTION_TYPES = [('check', 'Check'),
                     ('deposit', 'Deposit'),
                     ('transfer', 'Transfer'),
                     ('other', 'Other')]


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    ofxid = models.CharField(max_length=200, default='', editable=False)
    amount = models.FloatField('amount')
    notes = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateTimeField('date')
    ttype = models.CharField(max_length=15,
                             choices=TRANSACTION_TYPES,
                             null=False,
                             default='other')
    category = models.ForeignKey('Category', 
                                 null=True, blank=True, on_delete=models.SET_NULL)
    description = models.CharField(max_length=400, default='')
    payee = models.ForeignKey('Payee', null=True, blank=True, on_delete=models.SET_NULL)
    account = models.ForeignKey('Account', null=True, blank=True, on_delete=models.CASCADE)
    check_number = models.IntegerField('Check #', null=True, blank=True)
    incomplete = models.BooleanField('Incomplete', default=True)

    def is_complete(self):
        if self.payee is None or self.category is None:
            return False
        return True

    def is_incomplete(self):
        return not self.is_complete()

    def suggested_payee(self):
        sp = self.description[:25]
        if len(sp.split()) > 3:
            sp = ' '.join(sp.split()[:3])
        return string.capwords(sp)

    def suggested_lookup(self):
        return self.description[:25]

    def basic_json(self):
        return json_basic_serialize(self)

    def save(self, *args, **kwargs):
        self.incomplete = self.is_incomplete()
        super(Transaction, self).save(*args, **kwargs) # Call the "real"

    def __str__(self):
        return '({}) {} [{:.2f}]'.format(self.date.strftime("%Y-%m-%d"), self.description, self.amount) 


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200)
    ofxid = models.CharField(max_length=200, default='')    
    atype = models.ForeignKey('AccountType', on_delete=models.SET_NULL, null=True, blank=True)
    notes = models.CharField(max_length=200, null=True, blank=True)
    check_info = JSONField(blank=True, null=True, default=None)

    def __str__(self):
        return self.name

    def balance(self):
        return self.income() - self.expenses()

    def income(self):
        return totsum(self.transaction_set.filter(amount__gt=0))

    def expenses(self):
        return -totsum(self.transaction_set.filter(amount__lt=0))

    def ntransactions(self):
        return self.transaction_set.count()

    def last_transaction_date(self):
        return self.transaction_set.latest('date').date



class AccountType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    # eventually add the tax line or something


class TransactionType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200)
    parent_category = models.ForeignKey('Category', null=True, blank=True,
                                        related_name='subcategories',
                                        default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def path(self):
        return '/'.join(self.name.split(':')[:-1])

    def basename(self):
        return self.name.split(':')[-1]

    def basic_json(self):
        return json_basic_serialize(self)

class Payee(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200)
    default_category = models.ForeignKey('Category', null=True, blank=True, 
                                         on_delete=models.SET_NULL)
    # Comma-separated values
    lookup_strings = models.CharField(max_length=400, default='', blank=True)
    invoice_address = models.TextField(null=True, blank=True, default=None)
    invoice_email = models.EmailField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name

    def balance(self):
        return self.income() - self.expenses()

    def income(self):
        return totsum(self.transaction_set.filter(amount__gt=0))

    def expenses(self):
        return -totsum(self.transaction_set.filter(amount__lt=0))

    def ntransactions(self):
        return self.transaction_set.count()

    def last_transaction_date(self):
        try:
            return self.transaction_set.latest('date').date
        except:
            return datetime.datetime(1, 1, 2, 0, 0, tzinfo=pytz.timezone('UTC'))

    def basic_json(self):
        return json_basic_serialize(self)



class MyCheck(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    number = models.IntegerField(null=True, blank=True)
    payee = models.ForeignKey(Payee, on_delete=models.SET_NULL, null=True)
    amount = models.FloatField()
    date_created = models.DateTimeField()
    date_cashed = models.DateTimeField(null=True, blank=True)
    transaction = models.OneToOneField(Transaction, null=True, 
                                       on_delete=models.SET_NULL, blank=True)
    account = models.ForeignKey(Account, null=True, blank=True, on_delete=models.SET_NULL)
    notes = models.CharField(max_length=100, null=True, blank=True)
    to_print = models.BooleanField(default=False)


class Invoice(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    company = models.ForeignKey('MyCompany', on_delete=models.SET_NULL, default=None, null=True)
    payee = models.ForeignKey(Payee, on_delete=models.SET_NULL, null=True)
    recipient_address = models.TextField(null=True, blank=True, default=None)
    recipient_email = models.EmailField(null=True, blank=True, default=None) 
    amount = models.FloatField()
    date_created = models.DateTimeField()
    date_due = models.DateTimeField(null=True, blank=True)
    date_cashed = models.DateTimeField(null=True, blank=True)
    details = models.TextField(default=[])
    open_balance = models.FloatField()
    paid = models.BooleanField(default=False)
    notes = models.TextField(null=True, blank=True)

    def is_paid(self):
        return self.paid

    def items(self):
        items = json.loads(self.details)
        for i in range(len(items)):
            items[i]['amount'] = items[i]['quantity'] * items[i]['unit_price']
        return items



class PaymentType(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    invoice = models.ForeignKey(Invoice, null=True, on_delete=models.SET_NULL)
    ttype = models.ForeignKey(PaymentType, null=True, on_delete=models.SET_NULL)
    amount = models.FloatField()
    date_received = models.DateTimeField()
    notes = models.TextField(null=True, blank=True, default=None)
    transaction = models.ForeignKey(Transaction, null=True, on_delete=models.SET_NULL)


class Items(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=400)
    description = models.TextField(blank=True, null=True)
    unit_amount = models.FloatField()


class UserParamHolder(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    quick_add_category = models.ForeignKey(Category, on_delete=models.SET_NULL, 
                                            null=True, blank=True)


class MyCompany(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=400)
    address = models.TextField(null=True, blank=True, default=None)
    email = models.EmailField(null=True, blank=True, default=None) 
    logo = models.ImageField(null=True, blank=True, default=None)
    invoice_message = models.TextField(null=True, blank=True, default=None)
    invoice_subject = models.CharField(max_length=400, null=True, blank=True, default=None)
    smtp_host = models.CharField(max_length=400, null=True, blank=True, default=None)
    smtp_username = models.CharField(max_length=400, null=True, blank=True, default=None)

cashmgr/forms.py
from django.forms import ModelForm
from .models import Account, Payee, Category, MyCheck, Invoice, MyCompany
from django import forms


class Html5DateInput(forms.DateInput):
    input_type = 'date'


class UploadOfxForm(forms.Form):
    file = forms.FileField(label='OFX file')


class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = '__all__'


class PayeeForm(ModelForm):
    class Meta:
        model = Payee
        fields = ['name', 'lookup_strings']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'payeefield'}),
        }


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'categoryfield'}),
        }


class MyCheckForm(ModelForm):
    class Meta:
        model = MyCheck
        fields = ['number', 'date_created', 'amount', 'to_print']


class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        fields = ['recipient_address', 'recipient_email', 'date_created', 'date_due', 'notes', 'paid']
        widgets = {
            'recipient_address': forms.Textarea(attrs={'rows':3}),
            'date_created': Html5DateInput(),
            'date_due': Html5DateInput()
        }


class MyCompanyForm(ModelForm):
    class Meta:
        model = MyCompany
        fields =  '__all__'
        widgets = {
            'smtp_password': forms.PasswordInput(),
        }

cashmgr/templates/cashmgr/forms/add_account.html
{% extends 'cashmgr/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}New Account{% endblock %}

{% block head_block %}
  
  <script>
  
    $(document).ready( function() {
      //var file_content = window.opener.$('#file-content').length ? window.opener.$('#file-content').val();
    }); // -- end ready()

  </script>

{% endblock %}


{% block body_block %}

<div class="page-header">
  <h1>New Account</h1>
</div>

<div class="row">
  <div class="col">
    <form action="/cashmgr/add/account/" method="post">
      {% csrf_token %}
      <div class="form-group">
        {{ form.name.label_tag }}
        {{ form.name|add_class:"form-control" }}
      </div>
      <div class="form-group">
        <label for="id_atype">Account type</label>
        {{ form.atype|add_class:"form-control" }}
      </div>
      <div class="form-group">
        {{ form.notes.label_tag }}
        {{ form.notes|add_class:"form-control" }}
      </div>
      {% if ofxid %}
        <div class="form-group">
          {{ form.ofxid.label_tag }}
          {% render_field form.ofxid class="form-control" readonly="True" value=ofxid %}
        </div>
      {% endif %}
      <button type="submit" class="btn btn-primary" value="Upload"><span class="glyphicon glyphicon-save"></span> Save</button>
    </form>
  </div>
</div>

{% endblock %}

cashmgr/templates/cashmgr/forms/invoice_details.html
<html lang="en">
{% load static %}
{% load widget_tweaks %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% if target_invoice %}
    <title>Invoice n: {{ target_invoice.id }}</title>
  {% else %}
    <title>New Invoice</title>
  {% endif %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  
  <script>var jsdata = {{ jsdata }};</script>
  <script src="{% static 'cashmgr/common.js' %}"></script>
  <script src="{% static 'cashmgr/tviews_inline_change_callbacks.js' %}"></script>
  <script>
  
    $(document).ready( function() {

      function save_address(edt, field){
        var retval = false;
        var pname = $('input#payee').val();
        var value = edt.val();
        url = ('/cashmgr/change/Payee/' 
             + encodeURIComponent(pname)
             + '/text/'
             + encodeURIComponent(field)
             + '/');

        console.log(url);
      
        jQuery.ajax({
          url: url ,
          dataType: 'json',
          type: "POST",
          data: ({'value': value }),
          success: function (result) {  
            if (result.status == "ok"){
              console.log(result);
              retval = true;
            }else{
              alert('Error: could not save.');
            }
          },
          async: false
        });
        return retval;
      }


      function get_payee_details(pk){
        var details = {};
        jQuery.ajax({
          url: '/cashmgr/recordinfo/Payee/' + pk + '/',
          dataType: 'json',
          success: function (result) {  
            details = result;
          },
          async: false
        });
        return details;
      }


      function payee_change_callback(edt) {
        var new_name = edt.val();
        edt.val(edt.attr('originalvalue')); 
        jQuery.ajax({
          url: '/cashmgr/payee/exists/?name=' + encodeURIComponent(new_name),
          dataType: 'json',
          success: function (result) {  
            if (result.status == "ok"){
              edt.val(new_name);
              var details = get_payee_details(result.msg.id);
              console.log(details);
              $('#id_recipient_address').val(details.invoice_address);
              $('#id_recipient_email').val(details.invoice_email);
            }else{
              // the payee is not in the database, asks the user to add it or 
              // to rollback.
              confirm_dialog( 
                'The payee is not in the database.', 
                'Do you want to create a new payee named "' + new_name + '"?',
                function() { // called on dialog confirmation
                  window.open(
                    '/cashmgr/add/payee/?name=' + encodeURIComponent(new_name),
                    '_blank',
                    'height=260,width=450'
                  );
                },
                function() {}, // called on dialog dismiss
                edt // position of dialog
              );            
            }
          },
          async: false
        });
      }

      setup_autocomplete_fields(payee_change_callback, function(){});

      


      function get_items(){
        var items = [];
        $("tbody#itemlist > tr").each(function() {
          var iname = $(this).find(".item_name").val();
          var idesc = $(this).find(".item_description").val();
          var qty = $(this).find(".item_qty").val() * 1;
          var uval = $(this).find(".item_unitprice").val() * 1.0;
          items.push({'name': iname, 'description': idesc,
                      'unit_price': uval, 'quantity': qty});
        });
        return items;
      }


      $("form#invoiceform").submit(function(e) {
        var url = "/cashmgr/add/invoice/";
        
        console.log('submitted');
        $("#items").val(JSON.stringify(get_items()));

        $.ajax({
          type: "POST",
          url: url,
          dataType: 'json',
          data: $("form#invoiceform").serialize(), // serializes the form's elements.
          success: function(data)
          {
            $('#debugdiv').html(data);
            if (data.status == 'ok'){
              window.opener.postMessage(data.msg, '*');
              window.close();
            }else{
              alert('error in adding the form: ' + data.msg);
            }
          },
          error: function(errdata){
            console.log(errdata);
            $('#debugdiv').html(errdata.responseText);
          },
        });

        e.preventDefault();
      });


      // PREVIEW
      $("button#pdf_preview_btn").click(function() {
        $("#items").val(JSON.stringify(get_items()));
        var url = "/cashmgr/preview/invoice/?" + $("form#invoiceform").serialize();
        window.open(url);
      });      


      function update_amounts(){
        totval = 0.;
        var items = $("tbody#itemlist > tr").each(function() {
          var qty = $(this).find(".item_qty").val() * 1;
          var uval = $(this).find(".item_unitprice").val() * 1.0;
          $(this).find(".item_unitprice").val(uval.toFixed(2));
          var amt = qty*uval;
          $(this).find(".item_amount").html(amt.toFixed(2));
          totval += amt;
        });
        $("#total_amount").html(totval.toFixed(2)) ;
      }

      function newitem(){
        var emptyline = '<tr><td><input type="text" class="item_name"></td>' + 
                        '<td><input type="number" class="item_qty" value="1" style="text-align:right"></td>' +
                        '<td><input type="text" class="item_description"></td>' +
                        '<td><input type="number" step="0.01" class="item_unitprice" value="0.00" style="text-align:right"></td>' +
                        '<td style="text-align:right"><span class="item_amount">0.00</span></td>' +
                        '<td><a href="#" class="item_remove_btn"><span class="glyphicon glyphicon-trash"></span></a></td></tr>';
        $("tbody#itemlist").append(emptyline);
      }

      // -- Message listener
      function listener(event) {
          console.log(event.data);
          var msg = event.data;
          if (msg.request == "update") {
              for (var i = 0; i < msg.targets.length; ++i) {
                  var target = msg.targets[i];
                  console.log(target);

                  if (target.etype == "autocomplete") { // updates the autocomplete fields

                      if (target.uid == 'add') {
                        jsdata[target.field + '_names'].push(target.value);
                        if (target.field == "payee") { // got a signal from an added payee
                          var edt = $('input#payee');
                          if (edt) {
                              edt.val(target.value);
                          }
                        }
                      }

                      if (target.uid == 'replace') {
                        var index = items.indexOf(target.old_value);
                        if (index !== -1) {
                            items[index] = target.value;
                        }
                      }
                  }
              }
          }
      }
      // -- end message listener

      if (window.addEventListener) {
          addEventListener("message", listener, false)
      } else {
          attachEvent("onmessage", listener)
      }

      $("button#add_item_btn").on("click", newitem);
      $("table#itemtable").on("blur", ".item_qty, .item_unitprice", update_amounts);
      $("table#itemtable").on('click', '.item_remove_btn', function(event){
        $(event.target).closest("tr").remove();
        update_amounts();
      });

      update_amounts(); // in the case we already have some items


      $('#save_address').click(function(){
        var edt = $('textarea#id_recipient_address');
        if( save_address(edt, 'invoice_address') ){
          $('#save_address').html('<span class="glyphicon glyphicon-floppy-saved text-success"></span><span class="text-success"> Saved! </span>').fadeIn(100);
        }
      });

      $('#save_email').click(function(){
        var edt = $('#id_recipient_email');
        if( save_address(edt, 'invoice_email') ){
          $('#save_email').html('<span class="glyphicon glyphicon-floppy-saved text-success"></span><span class="text-success"> Saved! </span>').fadeIn(100);
        }
      });

    }); // -- end ready()

  </script>
</head>
<body>
<div class="container">

<div class="row">
  <div class="col col-xs-12">
    <div class="page-header" style="padding-top: 50px">
      {% if target_invoice %}
      <h1>Invoice n: {{ target_invoice.id }}</h1>
      {% else %}
      <h1>New Invoice</h1>
      {% endif %}
    </div>
  </div>
</div>


{% if target_invoice %}
<div class="row">
  <div class="col col-xs-12">
    <a href="/cashmgr/add/invoice/?duplicate={{ target_invoice.id }}" class="btn btn-info">
      <span class="glyphicon glyphicon-duplicate"></span> Create a duplicate
    </a>
  </div>
</div>
{% endif %}

<div class="row">
    <div class="col-sm-12">
    &nbsp;
    </div>
</div>


<form action="/cashmgr/add/invoice/" method="post" id="invoiceform">
  {% csrf_token %}
  <div class="form-group">
    <label for="payee">Payee</label>
    <input type="text" id="payee" name="payee" class="form-control" value="{% if model_invoice %}{{ model_invoice.payee.name }}{% endif %}" class="payeefield">    
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      {{ form.recipient_address.label_tag }}
      {{ form.recipient_address|add_class:"form-control" }}
      <a href="#" id="save_address" class="nounderline"><span class="glyphicon glyphicon-floppy-disk"></span> Save changes</a>
    </div>
    <div class="col-sm-6">
      {{ form.recipient_email.label_tag }}
      {{ form.recipient_email|add_class:"form-control" }}
      <a href="#" id="save_email" class="nounderline"><span class="glyphicon glyphicon-floppy-disk"></span> Save changes</a>
    </div>
  </div> 
  <div class="form-group row">
    <div class="col-sm-4">
    <label for="id_date_created">Date</label>
    {{ form.date_created|add_class:"form-control" }}
    </div>  
    <div class="col-sm-4">
    <label for="id_date_created">Due Date</label>
    {{ form.date_due|add_class:"form-control" }}
    </div>
  </div>
  

  {% if target_invoice %}
  <input id="target" type="hidden" name="target" value="{{ target_invoice.id }}">
  {% else %}
  <input id="target" type="hidden" name="target" value="-1">
  {% endif %}
  <input id="items" type="hidden" name="items">

  <div class="row">
    <div class="col-xs-12">
      <h2>Items</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <button class="btn btn-info" type="button" name="add_item_btn" id="add_item_btn"><span class="glyphicon glyphicon-plus-sign"></span> Add an item</button>
    </div>
  </div>
  <table class="table" id="itemtable">
    <thead>
      <th>Item<th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Unit price</th>
      <th>Amount</th>
    </thead>
    <tbody id="itemlist">
    {% if model_invoice %}
      {% for item in model_invoice.items %}
        <tr>
          <td><input type="text" class="item_name" value="{{ item.name }}"></td> 
          <td><input type="number" class="item_qty" value="{{ item.quantity }}" style="text-align:right"></td>
          <td><input type="text" class="item_description" value="{{ item.description }}"></td>
          <td><input type="number" step="0.01" class="item_unitprice" value="{{ item.unit_price }}" style="text-align:right"></td>
          <td style="text-align:right"><span class="item_amount"></span></td>
          <td><a href="#" class="item_remove_btn"><span class="glyphicon glyphicon-trash"></span></a></td>
        </tr>
      {% endfor %}
    {% endif %}
      
    </tbody>
    <tr>
        <th scope="row">Total</th>
        <td> </td><td> </td><td> </td>
        <td style="text-align:right"><span id="total_amount"></span></td>
      </tr>
  </table>



  <div class="form-group">
    {{ form.notes.label_tag }}
    {{ form.notes|add_class:"form-control" }}  
  </div>
  <div class="form-group">
    {{ form.paid.label_tag }}
    {{ form.paid|add_class:"form-check-input" }}  
  </div>

    <button class="btn btn-primary" type="button" id="pdf_preview_btn"><span class="glyphicon glyphicon-open-file"></span> PDF Preview</button> 
    <button class="btn btn-primary" type="submit" id="submit_btn"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>
    <button class="btn btn-primary" type="button" id="save_and_send_btn"><span class="glyphicon glyphicon-envelope"></span> Save and Send</button>
  
</form>


</body>
</html>